const API_BASE = window.PAWALERT_API_URL || (location.port === "8080" ? "" : "http://127.0.0.1:8080");
const EMAIL_API_BASE = window.PAWALERT_EMAIL_API_URL || "http://127.0.0.1:8081";
const setStatus = (form, text, type = "") => { const status = form.querySelector(".form-status"); status.textContent = text; status.className = `form-status ${type}`; };
async function post(path, body, base = API_BASE) { const response = await fetch(`${base}${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok || data.ok === false) throw new Error(data.error || "Something went wrong"); return data; }
async function sendReportConfirmation(report, details) { const user = JSON.parse(localStorage.getItem("pawalert_user") || "{}"); const email = user.email; if (!email) return; try { await post("/send_report_confirmation", { email, report_id: report.report_id, animal_type: details.animal_type, condition: details.condition, location: details.location }, EMAIL_API_BASE); } catch (error) { console.warn("Report was submitted but its email acknowledgement could not be sent.", error); } }
async function submitPendingReport() { const stored = sessionStorage.getItem("pawalert_pending_report"); if (!stored) return null; const details = JSON.parse(stored); const report = await post("/reports", details); sessionStorage.removeItem("pawalert_pending_report"); await sendReportConfirmation(report, details); return report; }
function reportComplete(report) { location.assign(report ? `success.html?report=${encodeURIComponent(report.report_id)}` : "success.html"); }
document.querySelectorAll("form[data-api]").forEach((form) => form.addEventListener("submit", async (event) => { event.preventDefault(); const mode = form.dataset.api; const values = Object.fromEntries(new FormData(form)); const button = form.querySelector("button"); button.disabled = true; try { if (mode === "report") { sessionStorage.setItem("pawalert_pending_report", JSON.stringify(values)); location.assign("login.html?next=report"); return; } if (mode === "login") { setStatus(form, "Logging you in..."); const user = await post("/login", values); localStorage.setItem("pawalert_user", JSON.stringify({ ...user, email: values.email })); const report = await submitPendingReport(); if (report) reportComplete(report); else setStatus(form, `Welcome back, ${user.name}.`, "success"); return; } if (!form.dataset.otpSent) { setStatus(form, "Sending verification code..."); const result = await post("/send_otp", { email: values.email, purpose: "signup" }, EMAIL_API_BASE); form.dataset.otpSent = "true"; form.querySelector(".otp-area").hidden = false; form.querySelector("[name=otp]").required = true; button.innerHTML = "Verify code and create account <span>-></span>"; setStatus(form, result.message || "Verification code sent.", "success"); return; } setStatus(form, "Verifying your code..."); await post("/verify_otp", { email: values.email, otp: values.otp }, EMAIL_API_BASE); const user = await post("/users", { name: values.name, email: values.email, password: values.password }); localStorage.setItem("pawalert_user", JSON.stringify({ ...user, email: values.email })); const report = await submitPendingReport(); if (report) reportComplete(report); else setStatus(form, "Account verified and created.", "success"); } catch (error) { const port = mode === "signup" && !form.dataset.otpSent ? "8081" : "8080"; setStatus(form, `${error.message}. Check that the required service is running on port ${port}.`, "error"); } finally { button.disabled = false; } }));
const successMessage = document.querySelector("#success-message"); if (successMessage) { const id = new URLSearchParams(location.search).get("report"); if (id) successMessage.textContent = `Report #${id} is now in the PawAlert queue. A confirmation email has also been requested.`; }
const cat = document.querySelector("#cat-companion"); if (cat) cat.style.setProperty("--cat-delay", `-${Math.round(performance.now() % 26000)}ms`);
